
tasks:
  - name: Install dependencies
    init: |
      python -m pip install --upgrade pip
      python -m pip install Django
      python -m pip install flake8
      python manage.py migrate

  - name: Lint with flake8
    command: |
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

  - name: Test
    command: |
      python manage.py check
      python -m unittest

vscode:
  extensions:
    - ms-python.python
