
tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install Django
      python manage.py migrate
    command: |
      cd aa_hu_test
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python