
tasks:
  - init: |
      python -m pip install --upgrade pip
      python -m pip install Django
      python -m pip install flake8
      python manage.py migrate
    command: |
      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
      python -m unittest
  
ports:
  - port: 8000
    visibility: private
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python